[build]
publish = "sources"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "18"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/iptv/:splat"

[[headers]]
  for = "/*.m3u8"
  [headers.values]
    Cache-Control = "no-cache"
